// =========================================================================
// BANCO DE FRASES MOTIVACIONAIS DA SOL ACADEMY (sol-frases.js)
// =========================================================================

const TODAS_AS_FRASES = [
    "Você está progredindo! Cada esforço de hoje é uma conquista para seu futuro. 🌞",
    "Seu potencial é maior do que você imagina. Continue avançando! 🌞",
    "Cada página lida é um passo a mais em direção ao seu sonho. 🌞",
    "Persistir é transformar pequenas vitórias em grandes conquistas. 🌞",
    "O estudo de hoje é a liberdade de escolha de amanhã. 🌞",
    "Você não precisa ser perfeito, só precisa continuar. 🌞",
    "O conhecimento que você busca hoje será sua força no futuro. 🌞",
    "Sua mente é como um músculo: quanto mais você a treina, mais forte ela fica. 🌞",
    "O esforço de hoje constrói as oportunidades de amanhã. 🌞",
    "Errar é parte do aprendizado, mas desistir nunca será. 🌞",
    "Grandes conquistas começam com pequenos hábitos de estudo. 🌞",
    "O futuro agradece o aluno dedicado que você escolhe ser hoje. 🌞",
    "Aprender é plantar sementes que darão frutos para a vida inteira. 🌞",
    "O conhecimento é a única riqueza que ninguém pode tirar de você. 🌞",
    "O cansaço passa, mas o orgulho de ter conseguido fica para sempre. 🌞",
    "Concentre-se no processo, e o resultado virá como consequência. 🌞",
    "Cada desafio vencido mostra que você está mais preparado do que pensa. 🌞",
    "Não compare sua jornada, cada aluno tem seu próprio ritmo. 🌞",
    "Avançar um pouco todos os dias vale mais do que parar esperando o momento perfeito. 🌞",
    "Você é capaz de aprender qualquer coisa, basta acreditar e praticar. 🌞",
    "Sua determinação é a chave que abre portas que parecem fechadas. 🌞",
    "Quando você estuda, está construindo pontes para seus sonhos. 🌞",
    "A disciplina é o caminho mais curto entre você e seu objetivo. 🌞",
    "Aprender é investir em si mesmo, e você é seu maior patrimônio. 🌞",
    "Lembre-se: você não está começando do zero, mas de onde parou ontem. 🌞",
    "Cada dúvida superada é uma vitória sobre o medo de errar. 🌞",
    "Não desista: até o passo mais lento ainda é movimento para frente. 🌞",
    "Cada dia de estudo é um tijolo no castelo dos seus sonhos. 🌞",
    "Estudar é transformar esforço em poder. 🌞",
    "Hoje pode ser difícil, mas você já está mais perto da sua vitória. 🌞",
    "O conhecimento abre portas que a força jamais conseguiria. 🌞",
    "Pequenos avanços diários constroem grandes resultados. 🌞",
    "Todo especialista já foi um iniciante que não desistiu. 🌞",
    "Estudar é acreditar que o amanhã pode ser melhor. 🌞",
    "Seu foco define sua direção, continue firme! 🌞",
    "A cada página estudada, um futuro mais claro se desenha. 🌞",
    "Estudar é um ato de coragem e amor próprio. 🌞",
    "A paciência e a disciplina sempre vencem a pressa. 🌞",
    "Nada pode parar um aluno determinado. 🌞",
    "Seus sonhos merecem a sua dedicação de hoje. 🌞",
    "O esforço pode ser silencioso, mas os resultados serão barulhentos. 🌞",
    "Grandes vitórias nascem da persistência em dias comuns. 🌞",
    "Não estude para passar, estude para aprender. 🌞",
    "Você já percorreu um longo caminho, siga em frente! 🌞",
    "A chave do sucesso é começar antes de se sentir pronto. 🌞",
    "Você é mais forte que as dificuldades que encontra. 🌞",
    "O saber é uma chama que nunca se apaga. 🌞",
    "Se você pode imaginar, também pode aprender. 🌞",
    "Estudar é plantar hoje para colher amanhã. 🌞",
    "O tempo dedicado ao aprendizado nunca é perdido. 🌞",
    "A educação é o passaporte para o futuro. 🌞",
    "Cada desafio enfrentado é uma prova de que você está evoluindo. 🌞",
    "Estudar é transformar curiosidade em poder. 🌞",
    "Você tem tudo o que precisa para conquistar o que deseja. 🌞",
    "O hábito de estudar hoje é o sucesso de amanhã. 🌞",
    "Quem estuda sempre encontra novos caminhos. 🌞",
    "Seu esforço é invisível para muitos, mas essencial para você. 🌞",
    "Estudar é acreditar no seu próprio crescimento. 🌞",
    "Nunca subestime o poder de uma hora bem estudada. 🌞",
    "Você está construindo um futuro brilhante, passo a passo. 🌞",
    "O sucesso nos estudos é a soma de pequenos esforços repetidos dia após dia. 🌞",
    "Não existe atalho para o conhecimento, mas cada passo na direção certa vale a pena. 🌞",
    "Sua mente é um universo de possibilidades. Continue explorando! 🌞",
    "A dedicação que você coloca agora é o alicerce da sua carreira amanhã. 🌞",
    "O estudo é o vento que impulsiona o barco das suas realizações. 🌞",
    "Quando o desânimo bater, lembre-se do motivo brilhante pelo qual começou. 🌞",
    "A melhor forma de prever o seu futuro é criá-lo através da educação. 🌞",
    "Semear conhecimento é a única garantia de colher sabedoria. 🌞",
    "Nenhuma pergunta é boba; bobeira é deixar o conhecimento passar em branco. 🌞",
    "Dificuldades preparam mentes comuns para destinos extraordinários. 🌞",
    "Um passo de cada vez. O topo da montanha só é alcançado assim. 🌞",
    "A única coisa impossível é aquela que você ainda não tentou aprender. 🌞",
    "Seu cérebro adora desafios. Alimente-o com novos conhecimentos hoje! 🌞",
    "Não tenha pressa de chegar, tenha propósito na caminhada de estudos. 🌞",
    "A revisão de hoje é a clareza de pensamento de amanhã. 🌞",
    "Você não está apenas lendo palavras, está decodificando o seu sucesso. 🌞",
    "Transforme o 'eu não sei' em 'eu ainda não aprendi'. 🌞",
    "A curiosidade é o motor da inteligência. Mantenha-a sempre ligada! 🌞",
    "Seja o protagonista da sua própria jornada acadêmica. 🌞",
    "O diploma é o troféu, mas o aprendizado diário é a verdadeira vitória. 🌞",
    "Conhecimento não ocupa espaço, mas expande horizontes. 🌞",
    "As horas debruçadas nos cadernos são o investimento com maior rentabilidade da vida. 🌞",
    "Aprender a aprender é a maior habilidade que você pode desenvolver. 🌞",
    "O erro de ontem é o acerto de amanhã, se você prestar atenção na lição. 🌞",
    "Você está afiando o seu machado. Quando chegar a hora, cortará a árvore de primeira! 🌞",
    "Foco é dizer não para várias coisas boas, para dizer sim à sua aprovação. 🌞",
    "O talento abre portas, mas a disciplina a mantém abertas. 🌞",
    "Respire fundo. Feche os olhos. Agora volte para a próxima página. Você consegue! 🌞",
    "Não foque no tamanho do edital, foque no parágrafo que está na sua frente. 🌞",
    "O orgulho de aprender algo difícil não tem preço. 🌞",
    "Você é o arquiteto da sua própria mente. Construa um castelo! 🌞",
    "Onde a motivação falha, o hábito de estudar triunfa. 🌞",
    "Ler é como viajar sem sair do lugar. Boa viagem no conteúdo de hoje! 🌞",
    "Um minuto de estudo é um minuto a menos de ignorância. 🌞",
    "Desafie-se um pouco mais hoje. A mágica acontece fora da zona de conforto. 🌞",
    "Se está difícil, é porque você está subindo de nível. 🌞",
    "O medo da prova desaparece quando a confiança no estudo aparece. 🌞",
    "A disciplina é a ponte entre as suas metas e as suas realizações. 🌞",
    "Quem se apaixona pelo processo de aprender não teme nenhuma avaliação. 🌞",
    "Você tem o controle do seu tempo. Use-o para esculpir o seu futuro. 🌞",
    "O aprendizado é um tesouro que seguirá o seu dono em qualquer lugar. 🌞",
    "A educação não muda o mundo, muda as pessoas que vão mudar o mundo. 🌞",
    "Sua capacidade de focar é o seu superpoder. Ative-o! 🌞",
    "Mais vale um estudo consistente de trinta minutos do que maratonas exaustivas. 🌞",
    "O cansaço é temporário. O diploma é para a vida toda. 🌞",
    "Não espere a inspiração para estudar. O estudo é que traz a inspiração. 🌞",
    "O conhecimento transforma o improvável em inevitável. 🌞",
    "Acorde com determinação, estude com foco e durma com satisfação. 🌞",
    "Seu progresso é invisível no dia a dia, mas gigantesco no longo prazo. 🌞",
    "Dúvidas são apenas o cérebro pedindo mais informações. Pergunte sempre! 🌞",
    "Você é mais resiliente do que a matéria mais difícil do curso. 🌞",
    "O segredo para avançar é simplesmente começar. Abra o material! 🌞",
    "De gota em gota, o oceano do conhecimento se enche. 🌞",
    "Não meça seu sucesso pelo que perdeu, mas pelo que aprendeu tentando. 🌞",
    "Transforme ansiedade em ação. O estudo acalma a mente que busca certezas. 🌞",
    "A excelência não é um ato, mas um hábito. Estude diariamente. 🌞",
    "Você não precisa ver a escada inteira, dê apenas o primeiro passo no estudo de hoje. 🌞",
    "O mestre já falhou mais vezes do que o iniciante sequer tentou. 🌞",
    "Foque naquilo que você pode controlar: a sua dedicação de hoje. 🌞",
    "Não deixe o que você não pode fazer interferir no que você pode aprender agora. 🌞",
    "Sua mente absorve o que você oferece a ela. Ofereça conhecimento de qualidade. 🌞",
    "O aprendizado começa exatamente onde a sua zona de conforto termina. 🌞",
    "Os obstáculos são aquelas coisas assustadoras que você vê quando tira os olhos do seu objetivo. 🌞",
    "Estar perdido no início de um assunto é o primeiro passo para se tornar um especialista nele. 🌞",
    "O conhecimento não tem linha de chegada. Aproveite a corrida! 🌞",
    "Acredite: todo o seu esforço fará sentido muito em breve. 🌞",
    "Estudar não é uma obrigação, é uma oportunidade de libertação. 🌞",
    "Valorize o seu processo. Ninguém dorme semente e acorda árvore. 🌞",
    "As raízes do estudo são amargas, mas os frutos são doces. 🌞",
    "A diferença entre o possível e o impossível está na sua vontade de estudar. 🌞",
    "Você está escrevendo a sua própria história de sucesso. Capriche no capítulo de hoje! 🌞",
    "Inteligência não é dom, é treino diário. 🌞",
    "Sua atitude diante dos estudos define a sua altitude na vida. 🌞",
    "Não desanime com a quantidade de matéria. Um parágrafo de cada vez e você chega lá. 🌞",
    "A clareza vem com a prática. Continue estudando! 🌞",
    "O único limite para a sua mente é aquele que você impõe. 🌞",
    "Não estude para ser o melhor da turma, estude para ser a sua melhor versão. 🌞",
    "Seja teimoso com os seus objetivos e flexível com os seus métodos de estudo. 🌞",
    "A maior descoberta da sua vida será o tamanho do seu próprio potencial. 🌞",
    "A procrastinação é ladra de sonhos. Não deixe ela roubar o seu tempo hoje! 🌞",
    "Comece onde você está, use o que você tem, aprenda o que você puder. 🌞",
    "Sua vontade de vencer deve ser maior que a preguiça de ler. 🌞",
    "O sucesso é o resultado de decisões que você toma quando ninguém está olhando. 🌞",
    "Uma mente que se abre a uma nova ideia jamais voltará ao seu tamanho original. 🌞",
    "Hoje é o dia perfeito para aprender algo que você achava difícil ontem. 🌞",
    "Quando você investe no seu cérebro, a vida devolve com juros. 🌞",
    "Respeite o seu ritmo, mas não pare de caminhar. 🌞",
    "Você é o único obstáculo entre você e o seu objetivo acadêmico. 🌞",
    "Lembre-se: grandes coisas levam tempo. Estude com paciência. 🌞",
    "O esforço que você sente hoje é a força que você sentirá amanhã. 🌞",
    "Celebre as pequenas vitórias: entender um conceito novo também é um troféu. 🌞",
    "Sua caneta e o seu caderno são as ferramentas que estão moldando o seu destino. 🌞",
    "Faça do estudo o seu hábito favorito e do sucesso a sua consequência natural. 🌞",
    "A única pessoa que você está destinado a se tornar é a pessoa que você decide aprender a ser. 🌞",
    "Em vez de se preocupar com a prova, ocupe-se com a preparação. 🌞",
    "Sua energia vai para onde o seu foco está. Direcione-a para os estudos hoje. 🌞",
    "O 'eu não consigo' é só o seu cérebro pedindo para você tentar de outro jeito. 🌞",
    "Nenhum conhecimento adquirido é em vão. Tudo se conecta no futuro. 🌞",
    "Você está blindando o seu futuro com educação. Ótimo trabalho! 🌞",
    "Nunca é tarde para ser aquilo que você sempre sonhou através dos estudos. 🌞",
    "A jornada acadêmica é uma maratona, não uma corrida de 100 metros. Mantenha o ritmo! 🌞",
    "A única coisa que cai do céu é chuva. O sucesso exige horas de estudo. 🌞",
    "Seu diploma vai ter a sua assinatura, mas será feito com o seu suor de hoje. 🌞",
    "Todo profissional brilhante que você admira passou por noites de estudo. 🌞",
    "Não espere que o caminho fique mais fácil, torne-se um estudante mais forte. 🌞",
    "Transforme o cansaço em motivação. O alívio da aprovação será imenso. 🌞",
    "Um estudante focado é como um trem-bala: nada consegue pará-lo. 🌞",
    "Se faltar motivação, estude com disciplina. A vontade vem durante a ação. 🌞",
    "Lembre-se: até a montanha mais alta é escalada um passo de cada vez. 🌞",
    "Não perca a aula de hoje, ela pode conter a chave para a porta de amanhã. 🌞",
    "O investimento no seu intelecto é o único que nunca sofre desvalorização. 🌞",
    "Seja a versão de si mesmo que você vai agradecer daqui a cinco anos. 🌞",
    "A verdadeira genialidade é apenas a paciência aplicada ao estudo. 🌞",
    "Pense nos seus estudos não como uma carga, mas como um combustível. 🌞",
    "Feche as distrações. Abra o livro. Escreva a sua história. 🌞",
    "Cada parágrafo que você lê é uma semente plantada na sua mente. 🌞",
    "A educação te dá o poder de reescrever a sua realidade. 🌞",
    "Seja exigente com as suas metas, e paciente com o seu progresso. 🌞",
    "A única competição válida nos estudos é contra quem você foi ontem. 🌞",
    "Não foque no 'ainda falta muito', celebre o 'olha o quanto eu já li'. 🌞",
    "Transforme suas dúvidas em pesquisas. Esse é o caminho da excelência. 🌞",
    "Hoje a matéria parece difícil, amanhã ela será apenas um conceito dominado. 🌞",
    "Tudo o que você precisa para aprender isso já está dentro de você. 🌞",
    "A persistência é o talento disfarçado de esforço diário. 🌞",
    "Um dia de estudo ruim é melhor do que um dia sem estudar nada. 🌞",
    "Não pare quando estiver cansado, pare quando o capítulo acabar. 🌞",
    "O seu foco de hoje vai pagar a sua paz de espírito de amanhã. 🌞",
    "Você está esculpindo o seu destino com cada linha que sublinha. 🌞",
    "Ninguém tira o que você tem na mente. Invista pesado nisso! 🌞",
    "Onde o talento não chega, o esforço contínuo ultrapassa. 🌞",
    "Sua resiliência é testada a cada página lida, e você está passando no teste! 🌞",
    "Se o conteúdo é complexo, comemore: você está elevando o seu nível. 🌞",
    "Foque em ser consistente. A velocidade virá naturalmente. 🌞",
    "Você tem uma mente brilhante, só precisa dar a ela as ferramentas certas. 🌞",
    "Pense na emoção de ver a tarefa como 'concluída'. Vale a pena! 🌞",
    "Não se assuste com o tamanho da floresta. Foque em podar a árvore à sua frente. 🌞",
    "A cada vídeo-aula assistida, o seu futuro bate palmas para você. 🌞",
    "As recompensas do estudo chegam sem aviso, mas chegam em abundância. 🌞",
    "A sorte favorece a mente que se preparou estudando. 🌞",
    "Transforme o 'tenho que estudar' em 'eu escolho crescer'. 🌞",
    "Desligue as notificações do mundo e ligue as conexões do seu cérebro. 🌞",
    "Um novo idioma, um novo cálculo, uma nova teoria... tudo isso expande a sua alma. 🌞",
    "Todo 'sim' para a preguiça é um 'não' para o seu sucesso. Diga SIM ao estudo! 🌞",
    "Quando a vontade de desistir bater, leia as suas anotações antigas e veja quanto já cresceu. 🌞",
    "O seu esforço inspira outras pessoas, mesmo que você não perceba. 🌞",
    "Você está criando uma base sólida. Edifícios altos precisam de alicerces profundos. 🌞",
    "Não deixe o fim de semana roubar todo o seu foco. Estude um pouquinho também. 🌞",
    "A clareza mental que o estudo proporciona é a melhor arma contra o medo do futuro. 🌞",
    "A inteligência é uma árvore que precisa ser regada com leitura diária. 🌞",
    "Seja corajoso o suficiente para admitir que não sabe, e humilde para aprender. 🌞",
    "O estudo é a ponte invisível entre o seu estado atual e a vida dos seus sonhos. 🌞",
    "Troque a desculpa de não ter tempo pela atitude de criar o seu tempo. 🌞",
    "A excelência acadêmica não é para poucos, é para aqueles que não desistem. 🌞",
    "Cada erro em um exercício é uma oportunidade disfarçada de aprender o certo. 🌞",
    "A recompensa do estudo não é apenas o que você ganha, mas quem você se torna. 🌞",
    "Pare de desejar que fosse mais fácil, e trabalhe para se tornar melhor. 🌞",
    "As grandes ideias nascem de mentes que foram bem alimentadas com conhecimento. 🌞",
    "Não há obstáculo intransponível para uma mente decidida a aprender. 🌞",
    "Sua capacidade de concentração aumenta toda vez que você ignora o celular para estudar. 🌞",
    "O que parece um sacrifício agora, será motivo de orgulho no futuro. 🌞",
    "Abrace a confusão mental inicial. É o seu cérebro abrindo espaço para o novo. 🌞",
    "Quando você sabe o porquê estuda, o 'como' estudar se torna muito mais fácil. 🌞",
    "Não importa quantas vezes você precisou reler a mesma linha, o importante é entender. 🌞",
    "O sucesso deixa pistas. O estudo consistente é a maior delas. 🌞",
    "Pense na alegria do momento em que a sua aprovação for publicada. 🌞",
    "Use as críticas que recebeu no passado como combustível para o seu estudo de hoje. 🌞",
    "O estudo te coloca em salas que a sorte jamais colocaria. 🌞",
    "Não limite os seus desafios, desafie os seus limites. 🌞",
    "Sua determinação deve ser tão alta quanto os objetivos que você traçou. 🌞",
    "Sempre parece impossível até que você termine o resumo. 🌞",
    "Você não estuda para armazenar dados, você estuda para libertar o seu pensamento. 🌞",
    "A diferença entre sonhar e realizar chama-se rotina de estudos. 🌞",
    "Quando você estuda em silêncio, o seu sucesso fala alto. 🌞",
    "O tempo vai passar de qualquer jeito. Que ele passe com você ficando mais sábio. 🌞",
    "Uma mente treinada é à prova de crises. Fortaleça a sua hoje. 🌞",
    "Não se desanime por estar na base da montanha, a vista de cima compensa a subida. 🌞",
    "Lembre-se: o papel e a caneta são armas de construção em massa de um futuro melhor. 🌞",
    "Nada substitui o trabalho duro. Nada substitui as horas de estudo. 🌞",
    "O aprendizado transforma as paredes da ignorância nas portas da oportunidade. 🌞",
    "Seja apaixonado por aprender, e você nunca deixará de crescer. 🌞",
    "Um estudante que confia no seu planejamento não teme a data da prova. 🌞",
    "Você está moldando o seu intelecto. Esse é o trabalho mais nobre que existe. 🌞",
    "A melhor vingança contra quem duvidou de você é um diploma na mão. 🌞",
    "Crie uma rotina de estudos tão boa que até a sua preguiça desista de te atrapalhar. 🌞",
    "O esforço diário pode ser rotineiro, mas os resultados dele serão extraordinários. 🌞",
    "A disciplina pesa gramas, mas o arrependimento de não ter estudado pesa toneladas. 🌞",
    "Cada linha que você lê é um degrau a menos na escada para o seu objetivo. 🌞",
    "Você não é apenas um aluno, você é um projeto de sucesso em construção. 🌞",
    "O seu futuro está escondido nas atividades que você escolhe fazer hoje. 🌞",
    "Não se preocupe em ser brilhante todos os dias, preocupe-se apenas em ser consistente. 🌞",
    "Mergulhe de cabeça no conteúdo de hoje. O oceano do saber é fascinante! 🌞",
    "O primeiro passo para o conhecimento é a vontade de aprender. Você já tem isso! 🌞",
    "Nunca é tarde para consertar o rumo dos estudos. Se hoje não foi bom, amanhã será. 🌞",
    "Respire, concentre-se, ataque a matéria. A vitória é sua! 🌞",
    "Acreditar que é possível já é metade do caminho percorrido. 🌞",
    "Não conte as horas que você estudou, faça as horas estudadas contarem. 🌞",
    "Os melhores livros de histórias são aqueles onde você é o herói que nunca desistiu. 🌞",
    "Sua força de vontade é mais forte do que a matéria mais densa. 🌞",
    "Em caso de dúvida, estude um pouco mais. 🌞",
    "O futuro sorri para quem prepara o próprio caminho. 🌞",
    "O sucesso é como construir um quebra-cabeça: cada dia de estudo é uma peça no lugar. 🌞",
    "Estudar é a melhor forma de organizar o caos das ideias. 🌞",
    "Nenhuma revisão é perda de tempo, é reforço da memória. 🌞",
    "O seu foco determina a rapidez com que você chegará lá. 🌞",
    "Aprenda algo novo todos os dias e, em um ano, você será uma pessoa irreconhecível. 🌞",
    "Deixar a preguiça de lado é o primeiro passo para o sucesso. 🌞",
    "Sua capacidade é ilimitada; só o que falta é colocar o estudo em prática. 🌞",
    "Você pode ter mil desculpas, mas só precisa de um bom motivo para abrir os livros. 🌞",
    "Lute pelos seus sonhos hoje com cadernos e apostilas. 🌞",
    "Não tenha medo de começar de novo, desta vez você não começa do zero, começa da experiência. 🌞",
    "Mantenha a cabeça baixa nos livros agora para andar de cabeça erguida amanhã. 🌞",
    "A educação é uma armadura invisível que te protege contra o fracasso. 🌞",
    "O conhecimento não exige força física, mas exige uma resistência mental gigantesca. 🌞",
    "O melhor professor que você pode ter é a sua própria curiosidade. 🌞",
    "Acredite na beleza dos seus sonhos de formatura! 🌞",
    "Uma hora a mais de estudo hoje pode ser a diferença que você precisa na hora da prova. 🌞",
    "Você já provou ser capaz de muitas coisas, dominar esse assunto é só mais uma delas. 🌞",
    "O estudo silencioso e concentrado é o ensaio para os aplausos da vitória. 🌞",
    "As grandes mentes foram moldadas em cadeiras confortáveis (ou desconfortáveis) lendo por horas. 🌞",
    "A sua aprovação não depende da sorte, depende exclusivamente de você. 🌞",
    "O esforço intelectual nunca é em vão, ele afia a sua inteligência para sempre. 🌞",
    "Concentre-se no seu objetivo, o restante é apenas distração. 🌞",
    "Não importa o quão devagar você vá, desde que não pare de estudar. 🌞",
    "Os frutos do estudo podem demorar a crescer, mas quando aparecem, são os mais doces. 🌞",
    "As horas que parecem arrastadas agora passarão voando quando você olhar para trás vitorioso. 🌞",
    "Você é do tamanho daquilo que você busca aprender. 🌞",
    "Nada de desânimo hoje! Tem um mundo de informações incríveis esperando por você. 🌞",
    "Com consistência, o impossível vira rotina. Continue focado! 🌞",
    "Cada dia é uma página em branco para escrever a sua história de aprovação. 🌞",
    "A chave de qualquer porta que você queira abrir no futuro está escondida dentro de um livro. 🌞",
    "Valorize a sua inteligência e a alimente bem. Bons estudos! 🌞"
];

// Se estiver rodando no navegador (Sol Passiva)
if (typeof window !== 'undefined') {
    window.SOL_FRASES = TODAS_AS_FRASES;
}

// Se estiver rodando no terminal pelo Node.js (Sol Ativa)
if (typeof module !== 'undefined') {
    module.exports = TODAS_AS_FRASES;
}